image: Visual Studio 2017

skip_tags: true

init:
  - git config --global core.autocrlf input

configuration: Release

build_script:
  - ps: .\build.ps1

on_failure:
  - ps: Update-AppveyorBuild -Version "$($Env:APPVEYOR_BUILD_VERSION).$($Env:APPVEYOR_BUILD_NUMBER)-fail"

for:
-
  branches:
    only:
      - master

  version: 0.0.1
  
-
  branches:
    except:
    - master

  version: 0.0.1.{build}-{branch}